dpo:
  max_num_epochs: 2
  max_num_steps: 20
  val_period: 50
  val_batches: 16
  val_global_batch_size: 32
  val_micro_batch_size: 1
  val_at_start: false
  seed: 42

  reference_policy_kl_penalty: 0.05
  preference_average_log_probs: False
  sft_average_log_probs: ${.preference_average_log_probs}
  preference_loss_weight: 1
  sft_loss_weight: 0.01

checkpointing:
  enabled: true
  checkpoint_dir: "results/dpo"
  metric_name: "val_loss"
  higher_is_better: false
  keep_top_k: 3
  save_period: 10000

policy:
  model_name: "meta-llama/Llama-3.1-8B-Instruct"
  tokenizer:
    name: ${policy.model_name}
  train_global_batch_size: 256
  train_micro_batch_size: 1
  max_total_sequence_length: 2048
  precision: "bfloat16"
  fsdp_offload_enabled: false
  activation_checkpointing_enabled: false

  dtensor_cfg:
    enabled: true
    cpu_offload: False
    sequence_parallel: false
    activation_checkpointing: false
    tensor_parallel_size: 2
    context_parallel_size: 1
    custom_parallel_plan: null
  
  dynamic_batching:
    enabled: False

  make_sequence_length_divisible_by: ${policy.dtensor_cfg.tensor_parallel_size}
  max_grad_norm: 1.0

  optimizer:
    name: "torch.optim.AdamW"
    kwargs:
      lr: 5.0e-6
      weight_decay: 0.1
      betas: [0.9, 0.98]
      eps: 1e-8
      foreach: False
      fused: False

  scheduler:
    - name: "torch.optim.lr_scheduler.LinearLR"
      kwargs:
        start_factor: 0.000000001
        end_factor: 1.0
        total_iters: 1
    - name: "torch.optim.lr_scheduler.ConstantLR"
      kwargs:
        factor: 1.0
        total_iters: 10000000000
    - milestones: [1]

data:
  dataset_name: "HelpSteer3"
  max_input_seq_length: ${policy.max_total_sequence_length}

logger:
  log_dir: "logs"
  wandb_enabled: true
  tensorboard_enabled: true
  mlflow_enabled: false
  monitor_gpus: true
  wandb:
    project: nemo-rl
    name: dpo-llama3.1-8b-instruct-4n8g-fsdp2tp1
  tensorboard: {}
  gpu_monitoring:
    collection_interval: 10
    flush_interval: 10

cluster:
  gpus_per_node: 8
  num_nodes: 4
