sft:
  max_num_epochs: 1
  max_num_steps: 500
  val_period: 10
  val_batches: 8
  val_global_batch_size: 32
  val_micro_batch_size: 1
  val_at_start: true
  seed: 42
checkpointing:
  enabled: true
  checkpoint_dir: results/sft-llama3.2-1b-1n8g-fsdp2tp1
  metric_name: val_loss
  higher_is_better: false
  keep_top_k: 3
  save_period: 10
policy:
  model_name: meta-llama/Llama-3.2-1B
  tokenizer:
    name: meta-llama/Llama-3.2-1B
    chat_template: '{% for message in messages %}{%- if message[''role''] == ''system''  %}{{''Context: '' + message[''content''].strip()}}{%- elif message[''role''] == ''user''  %}{{'' Question: '' + message[''content''].strip() + '' Answer:''}}{%- elif message[''role''] == ''assistant''  %}{{'' '' + message[''content''].strip()}}{%- endif %}{% endfor %}'
  train_global_batch_size: 32
  train_micro_batch_size: 1
  max_total_sequence_length: 1024
  precision: bfloat16
  dtensor_cfg:
    enabled: true
    cpu_offload: false
    sequence_parallel: false
    activation_checkpointing: false
    tensor_parallel_size: 1
    context_parallel_size: 1
    custom_parallel_plan: null
  dynamic_batching:
    enabled: false
  sequence_packing:
    enabled: false
  make_sequence_length_divisible_by: 1
  max_grad_norm: 1
  optimizer:
    name: torch.optim.AdamW
    kwargs:
      lr: 5e-06
      weight_decay: 0.1
      betas:
        - 0.9
        - 0.98
      eps: 1e-05
      foreach: false
      fused: false
data:
  max_input_seq_length: 1024
  dataset_name: squad 
  add_bos: true
  add_eos: true
  add_generation_prompt: false
logger:
  log_dir: logs/sft-llama3.2-1b-1n8g-fsdp2tp1
  wandb_enabled: true
  tensorboard_enabled: true
  mlflow_enabled: false
  monitor_gpus: true
  wandb:
    project: nemo-rl
    name: sft-llama3.2-1b-1n8g-fsdp2tp1
  tensorboard:
    log_dir: tb_logs-sft-dev-squad
  gpu_monitoring:
    collection_interval: 10
    flush_interval: 10
cluster:
  gpus_per_node: 8
  num_nodes: 1
