# GRPO Algorithm Configuration
defaults: "grpo_math_1B_megatron.yaml"

grpo:
  num_prompts_per_step: 64
  num_generations_per_prompt: 32

policy:
  model_name: "Qwen/Qwen3-30B-A3B"
  tokenizer:
    name: ${policy.model_name} ## specify if you'd like to use a tokenizer different from the model's default
  train_global_batch_size: 512
  train_micro_batch_size: 1
  generation_batch_size: 32 # Only used when generating using HF backend
  logprob_batch_size: 4
  max_total_sequence_length: 4096
  precision: "bfloat16"
  fsdp_offload_enabled: false
  activation_checkpointing_enabled: false

  dtensor_cfg:
    enabled: false

  optimizer: null # remove default FSDP optimizer

  scheduler: null # remove default FSDP scheduler

  megatron_cfg:
    enabled: true
    empty_unused_memory_level: 1
    converter_type: "LlamaForCausalLM"
    tensor_model_parallel_size: 4
    pipeline_model_parallel_size: 4
    context_parallel_size: 1
    expert_tensor_parallel_size: 1
    expert_model_parallel_size: 4
    sequence_parallel: True
    pipeline_dtype: ${policy.precision}

    optimizer:
      optimizer: "adam"
      lr: 3.0e-7
      min_lr: 3.0e-8
      weight_decay: 0.01
      bf16: true
      fp16: false
      params_dtype: "float32"

    scheduler:
      start_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      end_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      weight_decay_incr_style: "constant"
      lr_decay_style: "constant"
      lr_decay_iters: null
      lr_warmup_iters: 50
      lr_warmup_init: 3.0e-8
    
    env_vars:
      PYTORCH_CUDA_ALLOC_CONF: "expandable_segments:False"

  generation:
    backend: "vllm"
    max_new_tokens: ${policy.max_total_sequence_length}
    temperature: 1.0
    top_p: 1.0
    top_k: null
    stop_token_ids: null
    stop_strings: null
    vllm_cfg:
      tensor_parallel_size: 4
      gpu_memory_utilization: 0.8
      max_model_len: ${policy.max_total_sequence_length}

cluster:
  gpus_per_node: 8
  num_nodes: 8
